# Generated by Django 5.0.3 on 2024-03-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="descricao",
            field=models.TextField(null=True),
        ),
    ]
