# Generated by Django 5.0.3 on 2024-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0002_fotografia_categoria_alter_fotografia_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("NEBULOSA", "nebulosa"),
                    ("ESTRELA", "estrela"),
                    ("GALAXYA", "galaxya"),
                    ("PLANETA", "planeta"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
