# Generated by Django 5.0.3 on 2024-03-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0003_alter_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
    ]
